### ISSUE TITLE
Can not run it with python 3.6 and latest keras 

### ISSUE THREAD

**Issue by stevekwokdev** [hjpulkki/RPS#1]
Using TensorFlow backend.
Traceback (most recent call last):
  File "rpsFYP.py", line 45, in <module>
    model = simple_model()
  File "rpsFYP.py", line 17, in simple_model
    new_model.add(LSTM(units=64, input_shape=1, return_sequences=True, activation='sigmoid'))
  File "C:\Users\root\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\root\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\layers\recurrent.py", line 2185, in __init__
    **kwargs)
  File "C:\Users\root\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\layers\recurrent.py", line 408, in __init__
    super(RNN, self).__init__(**kwargs)
  File "C:\Users\root\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\base_layer.py", line 147, in __init__
    batch_size,) + tuple(kwargs['input_shape'])
TypeError: 'int' object is not iterable

**Comment by hjpulkki** [comment]
Thanks for bringing that up! I added a couple of commits to add support for the new versions of the libraries. There is now also a requirements.txt file, which you can use to get the exact same environment I was using. Can you get it working with those?

Nice to see that this project is still relevant and interesting to others!
